name: Client Compil

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up CMake
      run: sudo apt-get install cmake
    - name: Install SFML
      run: sudo apt-get install libsfml-dev
    - name: Install nlohmann/json
      run: sudo apt-get install nlohmann-json3-dev
    - name: Create build directory
      run: mkdir client/build
    - name: Configure and build
      working-directory: client/build
      run: cmake ..
    - name: Build
      working-directory: client/build
      run: make
