name: Server Compil

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout engine code
      uses: actions/checkout@v2
      with:
        repository: your/engine/repository

    - name: Configure and build engine
      run: |
        mkdir engine/build
        cd engine/build
        cmake ..
        make

  build_server:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout server code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: sudo apt-get install cmake

    - name: Install SFML
      run: sudo apt-get install libsfml-dev

    - name: Install nlohmann/json
      run: sudo apt-get install nlohmann-json3-dev

    - name: Create build directory
      run: mkdir server/build

    - name: Configure and build
      working-directory: server/build
      run: cmake ..

    - name: Build
      working-directory: server/build
      run: make